### ISSUE TITLE
task_control_t seems undefined

### ISSUE THREAD

**Issue by arBmind** [jeremyong/coop#1]
The promise type uses `task_control_t` to control allocations.

https://github.com/jeremyong/coop/blob/06da5d03068a5e36927d3b8cd2215d5e8a0820ba/include/coop/detail/promise.hpp#L164

But `task` has no definition for this. Am I missing something here?

**Comment by jeremyong** [comment]
Sorry about that! This was broken because a previous commit omitted this file (fixed in latest)
